---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud-release
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nextcloud-repo
      version: 5.5.2
  interval: 1m0s
  #values:
  valuesFrom:
    - kind: ConfigMap
      name: nextcloud-values
      valuesKey: values.yaml