---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: '>=2.15.2'
  install:
    crds: Create
  interval: 1h
  releaseName: sealed-secrets-controller
  targetNamespace: sealed-secrets
  upgrade:
    crds: CreateReplace
  #values:
