---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metric-server
  namespace: kube-system
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server-repo
      version: 3.12.2
  interval: 1m0s
  values:
    args:
      - --kubelet-insecure-tls=true
      - --kubelet-preferred-address-types=InternalIP